name: 'Nihongopod.com '
favicon: null
layout_spectrum: 0.021291
typography_spectrum: 0.768018
title: Nihogopod.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#CD5E4A'
    - '#84A7DD'
    - '#13090A'
    - '#3C4B14'
  brandStrength: 0.994369
  lightness: 0.903799
  saturation: 0.723165
  rhythmicContrast: 0.301247
purpose:
  - name: null
    item: null
    url: null
